# Generated by Django 5.0.6 on 2024-06-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_mediatour_image_alter_mediatour_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_image'),
        ),
        migrations.AlterField(
            model_name='mediatour',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tour_video'),
        ),
    ]
